config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    #get 'trade', to: 'items#trade_new'
    #get 'select', to: 'items#item_select'
    resources :relationships, only: [:index, :create, :destroy]
    resources :orders, only: [:index, :show, :create]
  end

  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '新品・未使用' },
    { id: 2, name: '未使用に近い' },
    { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' },
    { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :order

  has_many :item_relationships,
           class_name: 'Relationship',
           foreign_key: 'trade_item_id',
           dependent: :destroy,
           inverse_of: :item

  has_many :trad_item_relationships,
           class_name: 'Relationship',
           foreign_key: 'item_id',
           dependent: :destroy,
           inverse_of: :trade_item

  has_many :items, through: :item_relationships
  has_many :trade_items, through: :trad_item_relationships

  validates :image, presence: true
  validates :product_name, presence: true
  validates :description, presence: true
  validates :condition_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :pay_for_shipping_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :ken_name_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :shipping_days_id, numericality: { other_than: 0, message: "can't be blank" }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :condition
  belongs_to :pay_for_shipping
  belongs_to :ken_name
  belongs_to :shipping_days

  #def trade(other_item)
  #  relationships.find_or_create_by(trade_item_id: other_item.id) unless self == other_item
  #end

  #def untrade(other_item)
  #  relationship = relationships.find_by(tradeitem_id: other_item.id)
  #  relationship.destroy if relationship
  #end
end

app/models/ken_name.rb
class KenName < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' },
    { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' },
    { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' },
    { id: 7, name: '福島県' },
    { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' },
    { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' },
    { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' },
    { id: 17, name: '石川県' },
    { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' },
    { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' },
    { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' },
    { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' },
    { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' },
    { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' },
    { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :items
  has_many :ken_name
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :relationship
  validates :relationship_id, presence: true
end

app/models/pay_for_shipping.rb
class PayForShipping < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '着払い希望(購入者負担)' },
    { id: 2, name: '送料込み希望(出品者負担)' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :item, class_name: 'Item'
  belongs_to :trade_item, class_name: 'Item'
  has_one :order

  validates :item_id, presence: true
  validates :trade_item_id, presence: true
end

app/models/shipping_days.rb
class ShippingDays < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '1~2日で発送' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '4~7日で発送' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/shipping_info.rb
class ShippingInfo < ApplicationRecord
end

app/models/trade_item.rb
class TradeItem < ApplicationRecord
  belongs_to :item
  belongs_to :trade_item, class_name: 'Item'

  validates :item_id, presence: true
  validates :trade_item_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
  validates :nickname, presence: true

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :item_id_params, only: :update

  def index
    @items = Item.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to action: :index unless current_user.id == @item.user_id
  end

  def update
    if item_params[:item_id]
      binding.pry
      if @item.update(item_params)
        redirect_to item_path
      else
        render :edit
      end
    elsif item_id_params[:item_id]
      binding.pry
      if @my_items.update(item_id_params)
        redirect_to root_path
      else
        render :trade_new
      end
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :product_name, :description, :condition_id, :pay_for_shipping_id,
                                 :ken_name_id, :shipping_days_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :order_params, only: :create

  def index
    trade_items = Relationship.where(item_id: current_user.id)
    @my_item = Item.find(params[:item_id])
    @items = Item.where(id: trade_items.map(&:trade_item))
  end

  def show
    @order = Order.new
    @item = Item.find(params[:item_id])
    @relationship = Relationship.find_by(item_id: params[:id], trade_item_id: params[:item_id])
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to root_path
    else
      redirect_to root_path
      # render :show
    end
  end

  private

  def order_params
    params.permit(:relationship_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Collect</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <% if user_signed_in? %>
        <li><%= link_to '出品', new_item_path, class: "category-list" %></li>
        <li><%= link_to '出品商品', user_path(current_user.id), class: "category-list" %></li>
        <li><%= link_to '商品交換', item_orders_path(current_user.id), class: "category-list" %></li>
      <% end %>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"  %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>

  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>

app/views/trades/edit.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      交換する商品
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.product_name %>
        </h2>
      </div>
    </div>

    <%# 譲渡可能商品一覧の表示 %>
    <%= form_with model: @item, url:, local: true do |f| %>
    <%= form_with model: @order_shipping_info, url: item_orders_path(@item), id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

      <%# render 'shared/error_messages', model: f.object %>

      <div class='my-item-form'>
        <h1 class='info-input-haedline'>
          譲渡可能な商品
        </h1>

        <ul class='my-item-lists'>
          <% @my_items.each do |item| %>
            <li class='list'>
              <div class='my-item-info'>
                <%= image_tag item.image, class: 'my-item-img' %>
              </div>
              <div class='my-item-right-content'>
                <h2 class='my-item-text'>
                  <%= item.product_name %>
                  <label><%= f.radio_button :item_id, item.id %></label>
                </h2>
              </div>
            </li>
          <% end %>
        </ul>  
      </div>

      <div class='buy-btn'>
        <%= f.submit "決定" ,class:"buy-red-btn", id:"button" %>
      </div>
    <% end %>
    <%# /譲渡可能商品一覧の表示 %> 

  </div>
</div>
<%= render "shared/second-footer"%>

app/views/trades/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      交換する商品
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.product_name %>
        </h2>
      </div>
    </div>

    <%# 譲渡可能商品一覧の表示 %>
    <%= form_with model: @item, local: true do |f| %>
      <%# render 'shared/error_messages', model: f.object %>

      <div class='my-item-form'>
        <h1 class='info-input-haedline'>
          譲渡可能な商品
        </h1>
  
        <%# f.collection_select :trade_item, @my_items.all, :id, :product_name %>

        <ul class='my-item-lists'>
          <% @my_items.each do |item| %>
            <li class='list'>
              <div class='my-item-info'>
                <%= image_tag item.image, class: 'my-item-img' %>
              </div>
              <div class='my-item-right-content'>
                <h2 class='my-item-text'>
                  <%= item.product_name %>
                  <label><%= f.radio_button :item_id, item.id %></label>
                </h2>
              </div>
            </li>
          <% end %>
        </ul>  
      </div>

      <%# binding.pry %>

      <div class='buy-btn'>
        <%= f.submit "決定" ,class:"buy-red-btn", id:"button" %>
      </div>

    <% end %>
    <%# /譲渡可能商品一覧の表示 %> 

  </div>
</div>
<%= render "shared/second-footer"%>