config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    #get 'trade', to: 'items#trade_new'
    #get 'select', to: 'items#item_select'
    resources :relationships, only: [:index, :create, :destroy]
    resources :orders, only: [:index, :show, :create]
  end

  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '新品・未使用' },
    { id: 2, name: '未使用に近い' },
    { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' },
    { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :order

  has_many :item_relationships,
           class_name: 'Relationship',
           foreign_key: 'trade_item_id',
           dependent: :destroy,
           inverse_of: :item

  has_many :trad_item_relationships,
           class_name: 'Relationship',
           foreign_key: 'item_id',
           dependent: :destroy,
           inverse_of: :trade_item

  has_many :items, through: :item_relationships
  has_many :trade_items, through: :trad_item_relationships

  validates :image, presence: true
  validates :product_name, presence: true
  validates :description, presence: true
  validates :condition_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :pay_for_shipping_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :ken_name_id, numericality: { other_than: 0, message: "can't be blank" }
  validates :shipping_days_id, numericality: { other_than: 0, message: "can't be blank" }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :condition
  belongs_to :pay_for_shipping
  belongs_to :ken_name
  belongs_to :shipping_days

  #def trade(other_item)
  #  relationships.find_or_create_by(trade_item_id: other_item.id) unless self == other_item
  #end

  #def untrade(other_item)
  #  relationship = relationships.find_by(tradeitem_id: other_item.id)
  #  relationship.destroy if relationship
  #end
end

app/models/ken_name.rb
class KenName < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' },
    { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' },
    { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' },
    { id: 7, name: '福島県' },
    { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' },
    { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' },
    { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' },
    { id: 17, name: '石川県' },
    { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' },
    { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' },
    { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' },
    { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' },
    { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' },
    { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' },
    { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :items
  has_many :ken_name
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :relationship
  validates :relationship_id, presence: true
end

app/models/pay_for_shipping.rb
class PayForShipping < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '着払い希望(購入者負担)' },
    { id: 2, name: '送料込み希望(出品者負担)' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :item, class_name: 'Item'
  belongs_to :trade_item, class_name: 'Item'
  has_one :order

  validates :item_id, presence: true
  validates :trade_item_id, presence: true
end

app/models/shipping_days.rb
class ShippingDays < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '1~2日で発送' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '4~7日で発送' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/shipping_info.rb
class ShippingInfo < ApplicationRecord
end

app/models/trade_item.rb
class TradeItem < ApplicationRecord
  belongs_to :item
  belongs_to :trade_item, class_name: 'Item'

  validates :item_id, presence: true
  validates :trade_item_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
  validates :nickname, presence: true

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :item_id_params, only: :update

  def index
    @items = Item.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to action: :index unless current_user.id == @item.user_id
  end

  def update
    if item_params[:item_id]
      binding.pry
      if @item.update(item_params)
        redirect_to item_path
      else
        render :edit
      end
    elsif item_id_params[:item_id]
      binding.pry
      if @my_items.update(item_id_params)
        redirect_to root_path
      else
        render :trade_new
      end
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :product_name, :description, :condition_id, :pay_for_shipping_id,
                                 :ken_name_id, :shipping_days_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :order_params, only: :create

  def index
    trade_items = Relationship.where(item_id: current_user.id)
    @my_item = Item.find(params[:item_id])
    @items = Item.where(id: trade_items.map(&:trade_item))
  end

  def show
    @order = Order.new
    @item = Item.find(params[:item_id])
    @relationship = Relationship.find_by(item_id: params[:id], trade_item_id: params[:item_id])
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to root_path
    else
      redirect_to root_path
      # render :show
    end
  end

  private

  def order_params
    params.permit(:relationship_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :relationship_params, only: :create

  def index
    @relationship = Relationship.new
    @trade_item = Item.find(params[:item_id])
    @my_items = current_user.items
  end

  def create
    @relationship = Relationship.new(relationship_params)
    if @relationship.save
      redirect_to root_path
    else
      render :index
    end
  end

  def destroy
  end

  private

  def relationship_params
    params.permit(:item_id, :trade_item_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('logo.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
      <%# render 'shared/error_messages', model: f.object %>
      <%# 商品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /商品画像 %>
      <%# 商品名と商品説明 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :product_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>
      <%# 商品の詳細 %>
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        </div>
      </div>
      <%# /商品の詳細 %>
      <%# 配送について %>
      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:pay_for_shipping_id, PayForShipping.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:ken_name_id, KenName.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_days_id, ShippingDays.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        </div>
      </div>
      <%# /配送について %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', items_path(@item.id), class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>商品一覧</h2>
    <div class="subtitle" >
      
    </div>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.product_name %>
            </h3>
          </div>
          <% end %>
        </li>
      <% end %>    
    </ul>
  </div>
  <%# /商品一覧 %>
</div>

app/views/items/item_select.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>

    <%# 譲渡可能商品一覧の表示 %>
    <%= form_with url: "#" do |form| %>
      <%# render 'shared/error_messages', model: f.object %>

      <div class='my-item-form'>
        <h1 class='info-input-haedline'>
          譲渡可能な商品
        </h1>
  
        <ul class='my-item-lists'>
          <% @my_items.each do |item| %>
            <li class='list'>
              <div class='my-item-info'>
                <%= image_tag item.image, class: 'my-item-img' %>
              </div>
              <div class='my-item-right-content'>
                <h2 class='my-item-text'>
                  <%= item.product_name %>
                  <label><%= f.radio_button :item_id, item.id %></label>
                </h2>
              </div>
            </li>
          <% end %>
        </ul>  
      </div>

      <div class='buy-btn'>
        <%= f.submit "決定" ,class:"buy-red-btn", id:"button" %>
      </div>

    <% end %>
    <%# /譲渡可能商品一覧の表示 %> 

  </div>
</div>
<%= render "shared/second-footer"%>

app/views/items/my_items_show.html.erb
<%= render "shared/header" %>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.product_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>

    <% if current_user.id == @item.user_id %>
      <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
    <% else %>
      <%= link_to "交換画面に進む", item_trade_path(@item.id) ,class:"item-red-btn"%>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.pay_for_shipping.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.ken_name.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_days.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: items_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）,求めている商品:◯◯◯◯◯" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:pay_for_shipping_id, PayForShipping.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ken_name_id, KenName.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_days_id, ShippingDays.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/items/show.html.erb
<%= render "shared/header" %>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.product_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
        <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <% else %>
        <%= link_to "交換申請", item_relationships_path(@item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.pay_for_shipping.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.ken_name.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_days.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /商品の概要 %>


</div>

app/views/items/trade_new.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      交換する商品
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.product_name %>
        </h2>
      </div>
    </div>

    <%# 譲渡可能商品一覧の表示 %>
    <%= form_with model: @item,local: true do |f| %>
      <%# render 'shared/error_messages', model: f.object %>

      <div class='my-item-form'>
        <h1 class='info-input-haedline'>
          譲渡可能な商品
        </h1>
  
        <%# f.collection_select :trade_item, @my_items.all, :id, :product_name %>

        <ul class='my-item-lists'>
          <% @my_items.each do |item| %>
            <li class='list'>
              <div class='my-item-info'>
                <%= image_tag item.image, class: 'my-item-img' %>
              </div>
              <div class='my-item-right-content'>
                <h2 class='my-item-text'>
                  <%= item.product_name %>
                  <label><%= f.radio_button :item_id, item.id %></label>
                </h2>
              </div>
            </li>
          <% end %>
        </ul>  
      </div>

      <%# binding.pry %>

      <div class='buy-btn'>
        <%= f.submit "決定" ,class:"buy-red-btn", id:"button" %>
      </div>

    <% end %>
    <%# /譲渡可能商品一覧の表示 %> 

  </div>
</div>
<%= render "shared/second-footer"%>

app/views/orders/index.html.erb
<%= render "shared/header" %>

  <%# 商品一覧 %>
  <div class='item-contents'>

    <h2 class='title'>交換申請が来ている商品</h2>
    <div class="subtitle" >

    </div>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_order_path(item.id, @my_item) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.product_name %>
              </h3>
            </div>
          <% end %>
        </li>
      <% end %>    
    </ul>
  </div>
  <%# /商品一覧 %>

app/views/orders/show.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"trade_item-box-img" %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">商品名</th>
          <td class="detail-value"><%= @item.product_name %></td>
        </tr>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">説明</th>
          <td class="detail-value"><%= @item.description %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.pay_for_shipping.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.ken_name.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_days.name %></td>
        </tr>
      </tbody>
    </table>

    <%= form_with model: @order, url: item_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
      <%= hidden_field_tag :relationship_id, @relationship.id %>
      <div class='buy-btn'>
        <%= f.submit "交換" ,class:"buy-red-btn", id:"button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/relationships/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>

    <%# 譲渡可能商品一覧の表示 %>
    <%= form_with model: @item,local: true do |f| %>
      <%# render 'shared/error_messages', model: f.object %>

      <div class='my-item-form'>
        <h1 class='info-input-haedline'>
          譲渡可能な商品
        </h1>
        <ul class='my-item-lists'>
          <% @my_items.each do |item| %>
            <li class='list'>
              <div class='my-item-info'>
                <%= image_tag item.image, class: 'my-item-img' %>
              </div>
              <div class='my-item-right-content'>
                <h2 class='my-item-text'>
                  <%= item.product_name %>
                  <label><%= f.radio_button :trade_item_id, item.id %></label>
                </h2>
              </div>
            </li>
          <% end %>
        </ul>  
      </div>

      <%= hidden_field_tag :item_id, value: @trade_item.id %>

      <div class='buy-btn'>
        <%= f.submit "決定" ,class:"buy-red-btn", id:"button" %>
      </div>

    <% end %>
    <%# /譲渡可能商品一覧の表示 %> 

  </div>
</div>
<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>出品商品</h2>
    <div class="subtitle" >

    </div>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <h1 class='info-input-haedline'>

          <li class='list'>
            <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>

            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.product_name %>
              </h3>
            </div>
            <% end %>
          </li>
        </h1>
      <% end %>    
    </ul>
  </div>
  <%# /商品一覧 %>